spring:
  application:
    name: CTI-multimedia-system
  datasource:
    url: jdbc:mysql://localhost:3306/CTI_DB?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  thymeleaf:
    cache: false
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialec: org.hibernate.dialect.MySQL5Dialect

app:
  web-socket:
    destinationPrefixes: /topic
    prefixes: /app
    paths: /cti-websocket
  security:
    user: user
    password: password
  extension: video/mp4, image/jpeg, image/jpg, image/png, image/gif

logging:
  level:
    org:
      springframework:
        security: INFO

server:
  port: 80
